# Session 3

## Assignment

### Task 1

#### 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
# function to divide 2 nos.
def compute(x,y):
    try:
        # calculate the division and print result
        res = x/y
        print("Result = %f" %res)
        
    except ZeroDivisionError:
        # in case of zero division error
        print("Zero Division Error!\nEnter numbers greater than zero")
    
    finally:
        # to notify the end of program execution 
        print("End of Execution")
            

In [2]:
compute(5,0)

Zero Division Error!
Enter numbers greater than zero
End of Execution


In [3]:
compute(4,2)

Result = 2.000000
End of Execution


#### 2. Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [4]:
# define the list variables
subjects = ["Americans", "Indians"]
verbs = ["play", "watch"]
objects = ["Baseball", "Cricket"]

# to print the output in the given format
for i in subjects:
    for j in verbs:
        for k in objects:
            print(f'{i} {j} {k}')

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


### Task 2

#### 1. Write a function so that the columns of the output matrix are powers of the input vector.

#### The order of the powers is determined by the increasing boolean argument. Specifically, when
#### increasing is False, the i-th output column is the input vector raised element-wise to the power
#### of N - i - 1.

In [5]:
import numpy as np

# define function to create the Alexandre Theophile Vandermonde matrix
def atv_func(num,N=None,inc=False):
    
    # create a list
    res = list()
    
    # check if the user has specified no value for N
    if N==None:
        N = len(num)
        
    # to compute the Alexandre Theophile Vandermonde Matrix
    for i in num:
        res1 = []
        for j in range(N):
            if inc == True:
                res1.append(i**j)
            else:
                res1.append(i**(N-j-1))
        res.append(res1)
        
    # represent the list in the form of array
    res = np.array(res)
    
    # return the list
    return res

In [6]:
atv_func([1,2,3,5],3,False)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [7]:
atv_func([1,2,3,5])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [8]:
atv_func([2,3,4],2)

array([[2, 1],
       [3, 1],
       [4, 1]])